### ISSUE TITLE
Fix database connection fail message

### ISSUE THREAD

**Issue by kukgini** [AbsaOSS/vcxagencynode#132]
In 1.0.0 release of vcxagency-node, It seems that the default database has changed from postgres to mysql when switching to vdr-tools. However, if the database connection fails, it logs a wrong error message (`Couldn't connect to postgres, will try again after ${timeoutMs}ms.`). I can make a PR for this simple bug, but I need your opinion on whether the message is better to change from `postgres` to `mysql` or to use more ambiguous words (e.g. storage or database) in case mysql is replaced with postgres or a custom plugin.

**Comment by mirgee** [comment]
I think using `mysql` instead of `postgres` is fine (more ambiguous wording would be appropriate e.g. if the user could easily choose what database they use, but in this case the database is hardcoded by the programmer). PRs are welcome :)

**Comment by kukgini** [comment]
Resolved by (https://github.com/AbsaOSS/vcxagencynode/pull/133)
